# Generated by Django 3.2.18 on 2023-03-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliarUno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('fecha_de_nac', models.DateField()),
            ],
        ),
    ]
